---
# tasks file for ansible_user
- name: "Add the user {{ user_name }}"
  ansible.builtin.user:
    name: "{{ user_name }}"
    group: wheel

- name: Deploy ssh key
  ansible.posix.authorized_key:
    user: "{{ user_name }}"
    key: "{{ lookup('file', '{{ temporal_ssh_key }}.pub') }}"

- name: "Make {{ user_name }} as sudoer"
  community.general.sudoers:
    name: "{{ user_name }}"
    user: "{{ user_name }}"
    commands: ALL
    